schema:
  - http://localhost:3000/graphql
documents:
  - ./src/graphql/**/*.graphql
generates:
  ./src/graphql/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo